### ISSUE TITLE
Min/max swapped in two asserts

### ISSUE THREAD

**Issue by stephane-caron** [jrl-umi3218/eigen-gurobi#3]
Min and max are swapped in the asserts at lines [163](https://github.com/jrl-umi3218/eigen-gurobi/blob/master/src/Gurobi.cpp#L163) and [174](https://github.com/jrl-umi3218/eigen-gurobi/blob/master/src/Gurobi.cpp#L174) of ``Gurobi.cpp``.

**Comment by haudren** [comment]
Oh thanks, hadn't noticed. Fixed in 5150e46 !
