### ISSUE TITLE
more details about this repo?

### ISSUE THREAD

**Issue by ahundt** [jrl-umi3218/eigen-gurobi#6]
Does this integrate with Tasks? What are the advantages/disadvantages? also can the answers to these questions be added to the README.md?

**Comment by haudren** [comment]
To answer your questions:
- This does not integrate with Tasks directly, as Tasks lacks a `GurobiQPSolver` to do the actual problem construction.
- This repo was created as more of an experiment to see if Gurobi performance was satisfying. I never got to do any serious benchmarks, but it seems that the barrier algorithm (interior-point solver) used in Gurobi only performs well on sparse problems, which we are not generating right now. Note that Gurobi clearly outperforms its concurrents on very large sparse problems. Gurobi can also handle integer variables, but again, we do not use them for now, and they are not part of the API of `eigen-gurobi`.

**Comment by ahundt** [comment]
Thanks, that answered my questions perfectly!
